### ISSUE TITLE
Starting Demo locally throws error

### ISSUE THREAD

**Issue by Ippezrobert** [mifosio/demo-server#24] opened 2017-07-07 13:21 UTC
In a windows environment, when demo-server is started with java -jar -Ddemoserver.persistent=true demo-server-0.1.0-BUILD-SNAPSHOT.jar command, it doesn't start. It throws error as below

_19:38:09.666 [main] WARN o.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.s.b.c.e.j.JettyEmbeddedWebAppContext@1734f68{/provisioner/v1,file:///C:/Users/Skyline%20Technologies/AppData/Local/Temp/jetty-docbase.6976753875901215218.2020/,UNAVAILABLE}
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.mifos.anubis.config.AnubisSecurityConfigurerAdapter': Unsatisfied dependency expressed through method 'configureGlobal' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.mifos.anubis.security.IsisAuthenticatedAuthenticationProvider': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.mifos.anubis.provider.TenantRsaKeyProvider': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.mifos.anubis.repository.TenantAuthorizationDataRepository': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraSessionProvider' defined in io.mifos.core.cassandra.config.CassandraConnectorConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.mifos.core.cassandra.core.CassandraSessionProvider]: Factory method 'cassandraSessionProvider' threw exception; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9142 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1] Cannot connect))
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:648)_

**Comment by crain** [comment] 2017-07-07 14:45
@Ippezrobert, yes you can start with demoserver.persistent=false. All available parameter are described here: https://github.com/mifosio/demo-server.

**Comment by Ippezrobert** [comment] 2017-07-07 15:44
@crain , There is a strange behaviour. When i start the demo-server with the above, it creates a database 'seshat' and one empty table 'tenants'. Migration does not take place i.e other sql scripts are not triggered to execute.

Some where down the console (service-runner.log) i see error as below:-

_17:54:42.295 [main] INFO  ch.vorburger.mariadb4j.DB - Installation complete.
17:54:42.295 [main] INFO  ch.vorburger.mariadb4j.DB - Starting up the database...
17:54:42.296 [main] INFO  ch.vorburger.mariadb4j.DB - mysqld executable: C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe
17:54:42.296 [main] INFO  ch.vorburger.exec.ManagedProcess - Starting Program [C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, "--basedir=C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base", "--datadir=C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\data\3306", --port=3306] (in working directory C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base)
17:54:42.297 [main] INFO  ch.vorburger.exec.ManagedProcess - Thread will wait for "mysqld.exe: ready for connections." to appear in Console output of process Program [C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, "--basedir=C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base", "--datadir=C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\data\3306", --port=3306] (in working directory C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base) for max. 30000ms
17:54:42.521 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: Using mutexes to ref count buffer pool pages
17:54:42.523 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: The InnoDB memory heap is disabled
17:54:42.525 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
17:54:42.529 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: Compressed tables use zlib 1.2.3
17:54:42.531 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: Not using CPU crc32 instructions
17:54:42.536 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: Initializing buffer pool, size = 128.0M
17:54:42.553 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: Completed initialization of buffer pool
17:54:42.891 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:42 [Note] InnoDB: Setting log file .\ib_logfile101 size to 48 MB
17:54:44.492 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:44 [Note] InnoDB: Setting log file .\ib_logfile1 size to 48 MB
17:54:45.595 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Note] InnoDB: Renaming log file .\ib_logfile101 to .\ib_logfile0
17:54:45.598 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Warning] InnoDB: New log files created, LSN=1616697
17:54:45.615 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Note] InnoDB: Highest supported file format is Barracuda.
17:54:45.791 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Note] InnoDB: 128 rollback segment(s) are active.
17:54:45.884 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Note] InnoDB: Waiting for purge to start
17:54:45.958 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.19-67.0 started; log sequence number 1616908
17:54:45.960 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Note] Plugin 'FEEDBACK' is disabled.
17:54:45.964 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:45 [Note] Server socket created on IP: '::'.
17:54:46.098 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 170707 17:54:46 [Note] C:\Users\Skyline Technologies\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe: ready for connections.
17:54:46.098 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: Version: '10.0.13-MariaDB'  socket: ''  port: 3306  mariadb.org binary distribution
17:54:46.120 [main] INFO  ch.vorburger.mariadb4j.DB - Database startup complete.
18:00:04.593 [main] INFO  test-logger - Service 'provisioner-v1' started and not registered with Eureka.
18:02:09.639 [main] INFO  test-logger - Service 'identity-v1' started and registered with Eureka.
18:05:18.970 [main] INFO  test-logger - Service 'rhythm-v1' started and registered with Eureka.
18:07:25.451 [main] INFO  test-logger - Service 'office-v1' started and registered with Eureka.
18:10:34.840 [main] INFO  test-logger - Service 'customer-v1' started and registered with Eureka.
18:15:52.269 [main] INFO  test-logger - Service 'accounting-v1' started and not registered with Eureka.
18:19:02.297 [main] INFO  test-logger - Service 'portfolio-v1' started and registered with Eureka.
18:24:19.395 [main] INFO  test-logger - Service 'deposit-v1' started and not registered with Eureka._


**The Other Error logs**
_18:21:52.995 [DiscoveryClient-0] ERROR c.n.discovery.TimedSupervisorTask - task supervisor timed out
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)_

**Last Lines in Console**
_18:24:11.865 [AsyncResolver-bootstrap-executor-0] INFO  c.n.d.s.r.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
18:24:13.459 [pool-9-thread-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 1146, SQLState: 42S02
18:24:13.460 [pool-9-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Table 'seshat.khepri_beats' doesn't exist
Query is : select beatentity0_.id as id1_1_, beatentity0_.alignment_hour as alignmen2_1_, beatentity0_.application_identifier as applicat3_1_, beatentity0_.beat_identifier as beat_ide4_1_, beatentity0_.next_beat as next_bea5_1_, beatentity0_.tenant_identifier as tenant_i6_1_ from khepri_beats beatentity0_ where beatentity0_.next_beat<'2017-07-07 18:24:13.428'
18:24:35.922 [AsyncResolver-bootstrap-executor-0] INFO  c.n.d.s.r.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
Identity Service: http://localhost:2021/identity/v1
Office Service: http://localhost:2023/office/v1
Customer Service: http://localhost:2024/customer/v1
Accounting Service: http://localhost:2025/accounting/v1
Portfolio Service: http://localhost:2026/portfolio/v1
Deposit Service: http://localhost:2027/deposit/v1_

What could have gone wrong????

**Comment by crain** [comment] 2017-07-07 17:10
@Ippezrobert could you try to start with: 

java -jar -Ddemoserver.provision=true demo-server-0.1.0-BUILD-SNAPSHOT.jar

This should start the server with embedded datastores and provision a tenant called 'playground'. The error you are seeying is because rhythm(our service for scheduling tasks) has not been initialized which is part of the provision step.

**Comment by Ippezrobert** [comment] 2017-07-07 18:06
@crain , Still the above does not migrate database. Everthing runs till to a point where its starts with WARNING as below;
_0:45:12.646 [pool-9-thread-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 1146, SQLState: 42S02
20:45:12.647 [pool-9-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Table 'seshat.khepri_beats' doesn't exist
Query is : select beatentity0_.id as id1_1_, beatentity0_.alignment_hour as alignmen2_1_, beatentity0_.application_identifier as applicat3_1_, beatentity0_.beat_identifier as beat_ide4_1_, beatentity0_.next_beat as next_bea5_1_, beatentity0_.tenant_identifier as tenant_i6_1_ from khepri_beats beatentity0_ where beatentity0_.next_beat<'2017-07-07 20:45:07.686'_

When this error occurs, i have realized connection to mysql is cutoff and when i try to connect to the mysql, it can't since mysql is not running.

Please review the complete log attached for a better understanding.

[Console.txt](https://github.com/mifosio/demo-server/files/1131900/Console.txt)

**Comment by crain** [comment] 2017-07-10 15:31
@Ippezrobert - The error you are seeing about "seshat.khepri_beats" is not the cause that the demo-server is not working.
It looks like you are running in a timeout probably cassandra. As I can see from the logs you have very high startup times(e.g. 77 seconds) whereas a service should normally start in about 20-30 seconds on moderate hardware. 
The problem is that we don't know excactly where these timeouts happen and it would take some time to find out.

I am running the demo-server on my environment with a SSD without issues. So running the demo-server on an environment with a SSD hard drive could help.

We are aware of this issue but we are currently not investing time in this since this is as the name says a demo-server and not used in production.

If you want to use this in a production like environment please let me know as there will be other solutions for you.

**Comment by myrle-krantz** [comment] 2017-07-10 15:37
Hey @Ippezrobert I just recently upgraded my hardware precisely because of this problem. On my old computer with an HDD drive, the provisioner needed 40-50 seconds startup time, and the rest needed roughly 20 seconds per service, but once provisioning of tenants and permissions for the services started the whole thing choked. Individually the services run just fine, three at a time they were fine too.  But running all of them was too much for my old machine.

**Comment by Ippezrobert** [comment] 2017-07-10 15:52
@crain and @myrle-krantz , I was also thinking it was hardware issue because am running this on HP Probook 4530s i3. When I start the demo-server, my computer becomes slow and hangs at times.

I will try on another high performing machine. But optimizing the process for resources utilization might help.

**Comment by myrle-krantz** [comment] 2017-07-10 17:15
If you see a specific improvement we welcome pull requests.  But since this is currently performing well enough for our purposes, I'm going to close this issue.

**Closed by myrle-krantz** 2017-07-10 17:15 UTC
